### ISSUE TITLE
Dataset Links

### ISSUE THREAD

**Issue by sachitbatra** [wenischlab/MicroSuite#1]
I'm having trouble finding the datasets for setting up MicroSuite, it would be great if you could provide links to the datasets used for running the benchmark.

1. _~/MicroSuite/datasets/HDSearch/image_feature_vectors.dat -> Google Open Images Data Source_ : https://storage.googleapis.com/openimages/web/download.html
Could you mention the dataset to download from this page?

2. _~/MicroSuite/datasets/Router/twitter_requests_query_set.dat_

3. _~/MicroSuite/datasets/SetAlgebra/wordIDs_mapped_to_posting_lists.txt (the available tar file must first be extracted on your machine)_ : Which tar file includes this dataset?

4. _~/MicroSuite/datasets/Recommend/query_set.csv_

Thanks!

**Comment by Reylak** [comment]
I second this demand. I believe we have to get the Open Images [Extended dataset](https://storage.googleapis.com/openimages/web/extended.html) (it has close to 500k images, as mentioned in the paper), and then we generate ourselves the feature vectors using Inception v3. Could an author please confirm this?

Also, providing a complete script to generate the feature vectors would be fantastic!

**Comment by sjindal94** [comment]
Yes, I second this demand too

**Comment by akshithasriraman** [comment]
The datasets were hosted using git lfs earlier, but it appears like git lfs now supports only 2GB storage. Data sets have been temporarily relocated here - https://akshithasriraman.eecs.umich.edu/dataset/

**Comment by mkhairy** [comment]
In the dataset directory you mentioned, there are still missing files such as:
~/MicroSuite/datasets/Recommend/query_set.csv
~/MicroSuite/datasets/SetAlgebra/query_set.txt
~/MicroSuite/datasets/Recommend/query_set.csv
and the tar file used in SetAlgerba (Wikipedia file), you said in the readme tutorial "(the available tar file must first be extracted on your machine)" but I cannot find that tar file in the directory

Thanks!

**Comment by akshithasriraman** [comment]
I have replied to the separate issue you created.
