### ISSUE TITLE
Specify grpc version to use

### ISSUE THREAD

**Issue by AjayBrahmakshatriya** [wenischlab/MicroSuite#3]
It seems that the current version of grpc is not compatible with protobuf-3.2.0 or with the helper code in the bucket_service. Could you specify which exact release of grpc was used to build the repository?

I have tried using different protobuf versions (3.0, 3.1 and 3.2) and a few releases of grpc. But wasn't able to find an exact combination that works.

**Comment by DCchico** [comment]
@akshithasriraman I have correctly built it using the latest version of grpc and protobuf library. But you will need a few lines of new header files when actually building the 4 services. I have documented the whole process, if you need I can email it to you.

**Comment by akshithasriraman** [comment]
MicroSuite was built with grpc version 0.14.0. gRPC continues to be an evolving codebase and they often deprecate older functions without a lot of backward compatibility support.
